name: Enforce License Compliance

on:
  push:
    branches: [master, release/*]
  pull_request:
    branches: [master]

jobs:
  enforce-license-compliance:
    # don't run license compliance
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
