name: image
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - measure
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-image:
    permissions:
      packages: write
    runs-on: ubuntu-24.04

    env:
      IMG_VERSIONED: ghcr.io/measure-sh/symbolicator:${{ github.sha }}
      NIGHTLY_IMG_CACHE: ghcr.io/measure-sh/symbolicator:nightly
      BUILDER_IMG_CACHE: ghcr.io/measure-sh/symbolicator:builder

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker Login
        run: docker login --username '${{ github.actor }}' --password '${{ secrets.GITHUB_TOKEN }}' ghcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push OCI multi-platform image
        run: |
          set -euxo pipefail
          args=()
          if docker pull -q "$BUILDER_IMG_CACHE"; then
            args+=(--cache-from "$BUILDER_IMG_CACHE")
          fi
          if docker pull -q "$NIGHTLY_IMG_CACHE"; then
            args+=(--cache-from "$NIGHTLY_IMG_CACHE")
          fi
          docker buildx build \
            "${args[@]}" \
            --build-arg BUILD_KIT_INLINE_CACHE=1 \
            --platform linux/amd64,linux/arm64 \
            --tag "$NIGHTLY_IMG_CACHE" \
            --tag "$IMG_VERSIONED" \
            --push .

      - name: Retag as latest and push
        if: github.event_name != 'pull_request'
        run: |
          docker pull "$IMG_VERSIONED"
          docker tag "$IMG_VERSIONED" ghcr.io/measure-sh/symbolicator:latest
          docker push ghcr.io/measure-sh/symbolicator:latest
